#
# $Id: wnnstat.msg,v 1.1.2.3 1999/04/01 05:23:42 nakanisi Exp $
#
### FreeWnn is a network-extensible Kana-to-Kanji conversion system.
### This file is part of FreeWnn.
### 
### Copyright Kyoto University Research Institute for Mathematical Sciences
###                 1987, 1988, 1989, 1990, 1991, 1992
### Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
### Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
###
### Author: OMRON SOFTWARE Co., Ltd. <freewnn@rd.kyoto.omronsoft.co.jp>
###
### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2, or (at your option)
### any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with GNU Emacs; see the file COPYING.  If not, write to the
### Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
###
### Commentary:
###
### Change log:
###	'99/03/20	片山＠ＰＦＵ <kate@pfu.co.jp>
###		.msg ファイルに空行があると、msg_open で死ぬ。FreeWnn で enbug :-)
###
### Last modified date: 20,Mar.1999
###
1	Env No.\t環境名\t参照数\t付属語\t辞書数(辞書No.)\t\tファイル\n
2	Env No.\t環境名\t参照数\n
3	ユーザ名:ホスト名\t(ソケットNo.)\t環境番号\n
4	No.\t種類\tニックネーム\tファイル\t\n
5	No.種類\t正/逆\t語数\t更新(頻)使用 プライオリティ\t[ニックネーム]\tファイル[(頻度)]\t[パスワード(頻度)]\n
6	逆変換
7	正変換
8	不
9	可
10	中
11	停止
12	Fid\t種類\t場所\t参照数\t\tファイル名\n
13	辞書
14	頻度
15	付属語
