#
# $Id: wnnstat.msg,v 1.1.2.3 1999/04/01 05:47:54 nakanisi Exp $
#
### FreeWnn is a network-extensible Kana-to-Kanji conversion system.
### This file is part of FreeWnn.
### 
### Copyright Kyoto University Research Institute for Mathematical Sciences
###                 1987, 1988, 1989, 1990, 1991, 1992
### Copyright OMRON Corporation. 1987, 1988, 1989, 1990, 1991, 1992, 1999
### Copyright ASTEC, Inc. 1987, 1988, 1989, 1990, 1991, 1992
###
### Author: OMRON SOFTWARE Co., Ltd. <freewnn@rd.kyoto.omronsoft.co.jp>
###
### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2, or (at your option)
### any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with GNU Emacs; see the file COPYING.  If not, write to the
### Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
###
### Commentary:
###
### Change log:(in Japanese)
###	'99/03/20	ÊÒ»³¡÷£Ğ£Æ£Õ <kate@pfu.co.jp>
###		.msg ¥Õ¥¡¥¤¥ë¤Ë¶õ¹Ô¤¬¤¢¤ë¤È¡¢msg_open ¤Ç»à¤Ì¡£FreeWnn ¤Ç enbug :-)
###
### Last modified date: 20,Mar.1999
###
1	Env No.\tô¿èºÇØ\tÙ¶äùí°\tÅÆÎÎ\tâ¤Ì¨í°(â¤Ì¨No.)\t\tÅÆÇµ\n
2	Env No.\tô¿èºÇØ\tÙ¶äùí°\n
3	ÆîÅÂÇØ:¤â¤é¤í¤îÇØ\t(ÚÙÄÇNo.)\tô¿èºæÀî£\n
4	No.\tê¡ùË\tÎÃúË\tÅÆÇµ\t\n
5	No.ê¡ùË\tÆß/ØË\të£í°\tÊÕä»(ó¢)ËğÆî óÀÇ¿×È\t[Ï÷ê¢]\tÅÆÇµ[(ó¢Ğù)]\t[password(ó¢Ğù)]\n
6	ØËüÈßĞ
7	ÆßüÈßĞ
8	Äâ
9	Æ«
10	Äã
11	ØôÅÏ
12	Fid\tê¡ùË\tŞÛÇÙ\tÙ¶äùí°\t\tÅÆÇµÇØ\n
13	â¤Ì¨
14	ó¢Ğù
15	ë£ÎÎ
